import type { Product } from "@/features/products/types/product.types";

const defaultVolumes = (price: number): Product["volumes"] => [
  { id: "30ml", label: "30 ml", price: Math.max(price - 80, 100) },
  { id: "50ml", label: "50 ml", price: Math.max(price - 40, 140) },
  { id: "100ml", label: "100 ml", price },
];

export const mockProducts: Product[] = [
  {
    id: "fleur-de-lune",
    name: "Fleur de Lune",
    description: "A luminous floral composition of jasmine and white musk.",
    notes: "Floral / Jasmine & White Musk",
    price: 195,
    images: ["/images/products/fleur-de-lune.png"],
    category: "pure-extractions",
    scentFamily: "floral",
    occasion: "personal-use",
    options: [],
    volumes: defaultVolumes(195),
    scentAnatomy:
      "Fleur de Lune opens with dewy jasmine petals and settles into a soft veil of white musk that glows on the skin.",
    scentNotes: {
      top: "Bergamot, Pear Blossom",
      heart: "Jasmine Sambac, Orange Blossom",
      base: "White Musk, Soft Woods",
    },
    availableInAtelier: true,
  },
  {
    id: "santal-parchment",
    name: "Santal Parchment",
    description: "Warm sandalwood layered with cardamom.",
    notes: "Woody / Sandalwood & Cardamom",
    price: 220,
    images: [
      "/images/product-detail/santal-main.png",
      "/images/product-detail/santal-thumb-0.png",
      "/images/product-detail/santal-thumb-1.png",
      "/images/product-detail/santal-thumb-2.png",
    ],
    category: "pure-extractions",
    scentFamily: "woody",
    occasion: "evening",
    options: [],
    volumes: [
      { id: "30ml", label: "30 ml", price: 140 },
      { id: "50ml", label: "50 ml", price: 180 },
      { id: "100ml", label: "100 ml", price: 220 },
    ],
    scentAnatomy:
      "Santal Parchment wraps around the skin like vintage vellum paper. It opens with bright top notes, shifting to clean papyrus and warm, rich sandalwood that dry down into dry cardamom and amber.",
    scentNotes: {
      top: "Sicilian Bergamot, Pink Pepper",
      heart: "Egyptian Jasmine Sambac, Papyrus",
      base: "West Indian Sandalwood, Cardamom, Amber",
    },
    availableInAtelier: true,
  },
  {
    id: "noir-cocoon",
    name: "Noir Cocoon",
    description: "An oriental blend of tobacco and amber.",
    notes: "Oriental / Tobacco & Amber",
    price: 240,
    images: ["/images/products/noir-cocoon.png"],
    category: "private-reserve",
    scentFamily: "oriental",
    occasion: "wedding",
    options: [],
    volumes: defaultVolumes(240),
    scentAnatomy:
      "Noir Cocoon envelops the wearer in smoked tobacco leaf and molten amber that deepens into a nocturnal warmth.",
    scentNotes: {
      top: "Black Pepper, Incense",
      heart: "Tobacco Leaf, Rose Absolute",
      base: "Amber, Labdanum, Vanilla",
    },
    availableInAtelier: true,
  },
  {
    id: "sol-dor",
    name: "Sol d'Or",
    description: "A fresh coastal blend of bergamot and sea salt.",
    notes: "Fresh / Bergamot & Sea Salt",
    price: 185,
    images: ["/images/products/sol-dor.png"],
    category: "pure-extractions",
    scentFamily: "fresh",
    occasion: "personal-use",
    options: [],
    volumes: defaultVolumes(185),
    scentAnatomy:
      "Sol d'Or captures sunlit bergamot over mineral sea salt, finishing in a clean, coastal breeze.",
    scentNotes: {
      top: "Bergamot, Sea Salt",
      heart: "Neroli, Water Lily",
      base: "Driftwood, White Musk",
    },
    availableInAtelier: true,
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Rich oud deepened with saffron.",
    notes: "Woody / Rich Oud & Saffron",
    price: 310,
    images: ["/images/products/atelier-oud.png"],
    category: "atelier-oils",
    scentFamily: "woody",
    occasion: "gift-sets",
    options: [],
    volumes: defaultVolumes(310),
    scentAnatomy:
      "Atelier Oud is a dense composition of resinous oud and saffron threads, polished with dark woods.",
    scentNotes: {
      top: "Saffron, Rose Oxide",
      heart: "Oud, Patchouli",
      base: "Guaiac Wood, Ambergris Accord",
    },
    availableInAtelier: true,
  },
  {
    id: "rose-absolute",
    name: "Rose Absolute",
    description: "Damask rose balanced with cedar.",
    notes: "Floral / Damask Rose & Cedar",
    price: 205,
    images: ["/images/products/rose-absolute.png"],
    category: "private-reserve",
    scentFamily: "floral",
    occasion: "birthday",
    options: [],
    volumes: defaultVolumes(205),
    scentAnatomy:
      "Rose Absolute presents damask rose in full bloom, steadied by dry cedar and a soft powdery trail.",
    scentNotes: {
      top: "Pink Pepper, Lemon",
      heart: "Damask Rose, Peony",
      base: "Cedar, Soft Amber",
    },
    availableInAtelier: true,
  },
];
